apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  # namespace: delivery-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: delivery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: shared-service-config
          env:
            - name: SERVICE_PORT
              value: '3000'

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  # namespace: delivery-ns
spec:
  selector:
    app: delivery-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
