apiVersion: v1
kind: Namespace
metadata:
  name: restaurant-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: otel-ns
