apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: orders-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
      annotations:
        networkservicemesh.io/name: 'orders-service-ns'
        networkservicemesh.io/clients: 'restaurant-service-ns'
    spec:
      containers:
        - name: orders-service
          image: orders-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: shared-service-config
          env:
            - name: SERVICE_PORT
              value: '3000'
            - name: NSM_NETWORK_SERVICES
              value: 'orders-service-ns'

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: orders-ns
  annotations:
    networkservicemesh.io/name: 'orders-service-ns'
spec:
  selector:
    app: orders-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
